# Generated by Django 4.2.1 on 2024-05-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_discussions_social_disc_time_cr_b0540f_idx'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='discussion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='social.discussions'),
        ),
    ]
