# Generated by Django 4.2.1 on 2024-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('choice', models.CharField(choices=[('Google', 'Google'), ('Yandex', 'Yandex'), ('Dropbox', 'Dropbox'), ('GOOGLE_DISK', 'Google Диск'), ('YANDEX_DISK', 'Yandex Диск'), ('MAIL_CLOUD', 'Облако Mail'), ('SBERDISK', 'Сбердиск'), ('Telegram', 'Telegram'), ('VK', 'VK')], max_length=50)),
            ],
        ),
    ]
