# Generated by Django 4.2.1 on 2024-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
