# Generated by Django 4.2.1 on 2024-05-25 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_links_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='links',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания ссылки'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='links',
            index=models.Index(fields=['time_create'], name='links_links_time_cr_3a8a69_idx'),
        ),
    ]
