# Generated by Django 4.2.1 on 2024-05-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discussions',
            index=models.Index(fields=['time_create'], name='social_disc_time_cr_b0540f_idx'),
        ),
    ]
